In [1]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.tree import DecisionTreeClassifier, plot_tree #학습된나무를그림으로보여줌
from IPython.display import display
from sklearn.model_selection import train_test_split


loan_data = pd.read_csv('../datasets/decision/train_loan_80.csv')
display(loan_data.head())
loan_encoded = pd.get_dummies(loan_data, drop_first=True)
display(loan_encoded.head())
x = loan_encoded.drop(columns=['Loan_Status_Y'])
y = loan_encoded['Loan_Status_Y']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

#tree 200개
model = RandomForestClassifier(n_estimators=200, max_depth=5, random_state=42)
model.fit(x_train, y_train)
print(f'학습 데이터:{model.score(x_train, y_train)}')
print(f'테스트 데이터:{model.score(x_test, y_test)}')

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,Yes,0,Graduate,No,6000,2250.0,265.0,360.0,1.0,Semiurban,N
1,Male,Yes,0,Graduate,No,2958,2900.0,131.0,360.0,1.0,Semiurban,Y
2,Male,Yes,2,Graduate,No,6250,1695.0,210.0,360.0,1.0,Semiurban,Y
3,Male,Yes,0,Graduate,No,2083,3150.0,128.0,360.0,1.0,Semiurban,Y
4,Male,No,0,Graduate,No,4166,0.0,98.0,360.0,0.0,Semiurban,N

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender_Male,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,Property_Area_Semiurban,Property_Area_Urban,Loan_Status_Y
0,6000,2250.0,265.0,360.0,1.0,True,True,False,False,False,False,False,True,False,False
1,2958,2900.0,131.0,360.0,1.0,True,True,False,False,False,False,False,True,False,True
2,6250,1695.0,210.0,360.0,1.0,True,True,False,True,False,False,False,True,False,True
3,2083,3150.0,128.0,360.0,1.0,True,True,False,False,False,False,False,True,False,True
4,4166,0.0,98.0,360.0,0.0,True,False,False,False,False,False,False,True,False,False

학습 데이터:0.8188775510204082
테스트 데이터:0.8383838383838383

In [3]:
#중요도 값 추출
importances_loan = model.feature_importances_
#상위 5개
top_5_idx = np.argsort(importances_loan)[::-1][:5]
top_5_df = pd.DataFrame({
    '평가 기준feature':x.columns[top_5_idx], '결정 영향도: ':importances_loan[top_5_idx]})
display(top_5_df)

        평가 기준feature  결정 영향도:
0     Credit_History  0.434101
1    ApplicantIncome  0.122768
2         LoanAmount  0.110170
3  CoapplicantIncome  0.083959
4   Loan_Amount_Term  0.055920